apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-workload-identity
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  serviceAccountName: service-account-name-placeholder
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3
        ports:
        - containerPort: 80
